<?php

/**
 * PluginsfKoreroChannelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfKoreroChannelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfKoreroChannelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfKoreroChannel');
    }
}