<?php

/**
 * PluginsfKoreroMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfKoreroMessageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfKoreroMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfKoreroMessage');
    }
}