<?php

/**
 * PluginsfKoreroChannel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id$
 */
abstract class PluginsfKoreroChannel extends BasesfKoreroChannel
{
	public static function getChannels()
	{
		return Doctrine_Query::create()
			->select('c.*')
			->from('sfKoreroChannel c')
			->execute(null, Doctrine_Core::HYDRATE_ARRAY);
	}
	
	public function getMessages($since = null, $user_id = null)
	{
		$q = Doctrine_Query::create()
			->select('m.*, u.username')
			->from('sfKoreroMessage m')
			->innerJoin('m.sfGuardUser u')
			->where('m.channel_id = ?', $this->getId())
			->orderBy('m.created_at DESC');
			
		if ($since)
		{
			$q->andWhere('m.created_at > ?', date('c', $since));
			$q->andWhere('m.user_id <> ?', $user_id);
		}
		else
		{
			$q->limit(20);
		}
		
		return $q->execute(null, Doctrine_Core::HYDRATE_ARRAY);
	}
}