<?php

/**
 * PluginsfKoreroUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfKoreroUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfKoreroUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfKoreroUser');
    }
}