channel:
  class:   sfDoctrineRouteCollection
  options: { model: sfKoreroChannel, module: sfKoreroChannel, prefix_path: /channel }

channel_show_channel:
  url:     /channel/:slug
  class:   sfDoctrineRoute
  options: { model: sfKoreroChannel, type: object }
  param:   { module: sfKoreroChannel, action: show }

message:
  class:   sfDoctrineRouteCollection
  options: { model: sfKoreroMessage, module: sfKoreroMessage, prefix_path: /message }
